Document: johnny
Title: Debian johnny Manual
Author: <insert document author here>
Abstract: This manual describes what johnny is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/johnny/johnny.sgml.gz

Format: postscript
Files: /usr/share/doc/johnny/johnny.ps.gz

Format: text
Files: /usr/share/doc/johnny/johnny.text.gz

Format: HTML
Index: /usr/share/doc/johnny/html/index.html
Files: /usr/share/doc/johnny/html/*.html
